import 'aframe'
import './components/shoot.component'
import './components/keyboardcontrols.component'
import './components/enemy.component'
import './components/selfdestruct.component'
import './components/missile.component'
import './components/gun.component'